services:
  template-graphql-web:
    build: ./docker/web
    container_name: template-graphql-web
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    environment:
      - APP_TIMEOUT=60
      - PHP_MEMORY_LIMIT=1024M
      - PHP_MAX_UPLOAD=10M
    ports:
      - "8080:80"
      - "5180:5180"
    platform: linux/x86_64

  template-graphql-db:
    build: ./docker/db
    container_name: template-graphql-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: Asia/Tokyo
    ports:
      - "3310:3306"
    platform: linux/x86_64

  template-graphql-redis:
    container_name: template-graphql-redis
    image: redis:7.0
    ports:
        - "6400:6379"
    volumes:
        - ./redis_volumes:/redis/data
    platform: linux/x86_64

  template-graphql-minio:
    container_name: template-graphql-minio
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    environment:
        - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
        - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    ports:
        - "9010:9010"
        - "9011:9011"
    volumes:
        - ./minio_volumes:/minio/data
    command: server --address ":9010" --console-address ":9011" /minio/data
    platform: linux/x86_64
