services:
  web:
    build: ./docker/web
    container_name: template_web
    env_file:
      - .env
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    environment:
      - APP_TIMEOUT=60
      - PHP_MEMORY_LIMIT=1024M
      - PHP_MAX_UPLOAD=10M
    ports:
      - "8080:80"
      - "5180:5180"
    platform: linux/x86_64

  db:
    build: ./docker/db
    container_name: template_db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
      TZ: Asia/Tokyo
    ports:
      - "3310:3306"
    platform: linux/x86_64

  redis:
      container_name: template_redis
      image: redis:7.0
      ports:
          - "6400:6379"
      volumes:
          - ./redis_volumes:/data
      platform: linux/x86_64
