#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

docker exec template-graphql-web npm run prettier
docker exec template-graphql-web npm run eslint
docker exec template-graphql-web ./vendor/bin/pint
git add .
